### PR TITLE
prep-release-notes: simple automated notes

### PR DESCRIPTION
**Pull request by mbolivar**
We're going to do the big detailed blog posts separately from mergeups from now on. Let's just print some simple information on what changed.

### CODE REVIEW

**Comment by mike-scott** [comment]
Kicking the tires on this.

**Comment by mbolivar** [comment]
let's see if this comment shows up on slack

**Comment by mbolivar** [comment]
testing if closing the PR shows up on slack

**Comment by mike-scott** [comment]
Ran the notes today, double-checking that the format will look similar to LmP notes

**Comment by mike-scott** [comment]
I think this is good, until we get more feedback to make improvements

**Review by mike-scott — APPROVED** [review]

**Pull request merged**
